### ISSUE TITLE
Updated for latest YouTube video.

### ISSUE THREAD

**Issue by mikeroyal** [ironicbadger/ironicbadger#1]
Hi, Alex @ironicbadger

Here's the markdown for your latest video just paste the markdown above your last video.
```
[![LibreSpeed: The Local Speed Test App with a Difference | A Self-Hosted App Spotlight](https://ytcards.demolab.com/?id=zyBT_nOnsKA&lang=en&background_color=%230d1117&title_color=%23ffffff&stats_color=%23dedede&width=240&duration=886 "LibreSpeed: The Local Speed Test App with a Difference | A Self-Hosted App Spotlight")](https://www.youtube.com/watch?v=zyBT_nOnsKA)
```
[![LibreSpeed: The Local Speed Test App with a Difference | A Self-Hosted App Spotlight](https://ytcards.demolab.com/?id=zyBT_nOnsKA&lang=en&background_color=%230d1117&title_color=%23ffffff&stats_color=%23dedede&width=240&duration=886 "LibreSpeed: The Local Speed Test App with a Difference | A Self-Hosted App Spotlight")](https://www.youtube.com/watch?v=zyBT_nOnsKA)

**Comment by ironicbadger** [comment]
Thank you so much for this. Super cool to see this issue! 👍 

I took it one step further and automated it.
https://github.com/ironicbadger/ironicbadger/blob/main/.github/workflows/youtube-cards.yml
